### ISSUE TITLE
Make AppKit optional to run the examples

### ISSUE THREAD

**Issue by sneetsher** [brysontyrrell/MacAdmins-2016-Craft-GUIs-with-Python-and-Tkinter#1]
Thank you for the nice lecture. I followed it because its examples should be generic and can run in any OS with Python.

However, I got this error message:

```
Traceback (most recent call last):
  File "/home/user/Desktop/doc_tk/MacAdmins-2016-Craft-GUIs-with-Python-and-Tkinter/01 - Basic Appearance/01_Basic_Appearance.py", line 2, in <module>
    import AppKit
ImportError: No module named AppKit
>>> 
```
I'm using Ubuntu 16.04 and AppKit seems a Mac specific module (`pip install appkit` brings me another different module).

So is it possible to change code to make AppKit optional.

**Comment by brysontyrrell** [comment]
Glad you enjoyed. This repository is a companion to a Mac admin conference: https://youtu.be/Wb1YFgHqUZ8

As the presentation links back here and it is Mac focused I won't be making changes here but I do see you made to your fork achieve this:
https://github.com/sneetsher/MacAdmins-2016-Craft-GUIs-with-Python-and-Tkinter
